# See: https://taskfile.dev/#/usage
version: "3"

vars:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
  # Path of the project's primary Go module:
  DEFAULT_GO_MODULE_PATH: .
  DEFAULT_GO_PACKAGES:
    sh: |
      echo $(
        cd {{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}} &&
        go list ./... | tr '\n' ' ' ||
        echo '"ERROR: Unable to discover Go packages"'
      )
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/npm-task/Taskfile.yml
  # Path of the project's primary npm-managed project:
  DEFAULT_NPM_PROJECT_PATH: .

tasks:
  check:
    desc: Check for problems with the project
    deps:
      - task: general:check-spelling
      - task: go:lint
      - task: markdown:check-links
      - task: markdown:lint
      - task: markdown:toc
      - task: poetry:validate

  fix:
    desc: Make automated corrections to the project's files
    deps:
      - task: general:correct-spelling
      - task: general:format-prettier
      - task: go:fix
      - task: go:format
      - task: markdown:fix
      - task: poetry:sync

  docs:generate:
    desc: Create all generated documentation content
    run: when_changed
    # This is an "umbrella" task used to call any documentation generation processes the project has.
    # It can be left empty if there are none.

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
  general:check-spelling:
    desc: Check for commonly misspelled words
    deps:
      - task: poetry:install-deps
        vars:
          POETRY_GROUPS: dev
    cmds:
      - |
        if
          ! poetry run \
            codespell
        then
          echo
          echo "If this was a false positive, add the word to the ignore list:"
          echo "https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/spell-check-task.md#false-positives"
          exit 1
        fi

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
  general:correct-spelling:
    desc: Correct commonly misspelled words where possible
    deps:
      - task: poetry:install-deps
        vars:
          POETRY_GROUPS: dev
    cmds:
      - |
        poetry run \
          codespell \
            --write-changes

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
  general:format-prettier:
    desc: Format all supported files with Prettier
    deps:
      - task: npm:install-deps
        vars:
          PROJECT_PATH: .
    cmds:
      - |
        npx \
          prettier \
            --write \
            .

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
  go:fix:
    desc: |
      Modernize usages of outdated APIs.
      Environment variable parameters:
      - GO_MODULE_PATH: Path of the Go module root (default: {{.DEFAULT_GO_MODULE_PATH}}).
      - GO_PACKAGES: List of Go packages to modernize (default: all packages of the module).
    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
    cmds:
      - go fix {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
  go:format:
    desc: |
      Format Go code.
      Environment variable parameters:
      - GO_MODULE_PATH: Path of the Go module root (default: {{.DEFAULT_GO_MODULE_PATH}}).
      - GO_PACKAGES: List of Go packages to modernize (default: all packages of the module).
    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
    cmds:
      - go fmt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
  go:lint:
    desc: |
      Lint Go code
      Environment variable parameters:
      - GO_MODULE_PATH: Path of the Go module root (default: {{.DEFAULT_GO_MODULE_PATH}}).
    dir: "{{default .DEFAULT_GO_MODULE_PATH .GO_MODULE_PATH}}"
    cmds:
      - |
        if
          ! which golangci-lint \
          &>/dev/null
        then
          echo "golangci-lint not installed or not in PATH."
          echo "Please install: https://golangci-lint.run/usage/install/#local-installation"
          exit 1
        fi
      - golangci-lint run

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:check-links:
    desc: Check for broken links
    vars:
      # The command is defined in a Taskfile variable to allow it to be broken into multiple lines for readability.
      # This can't be done in the `cmd` object of the Taskfile because `npx --call` uses the native shell, which causes
      # standard newline escaping syntax to not work when the task is run on Windows.
      #
      # Using -regex instead of -name to avoid Task's behavior of globbing even when quoted on Windows
      # The odd method for escaping . in the regex is required for windows compatibility because mvdan.cc/sh gives
      # \ characters special treatment on Windows in an attempt to support them as path separators.
      #
      # prettier-ignore
      CHECK_LINKS_COMMAND:
        "
          find . \
            -type d -name \".git\" -prune -o \
            -type d -name \".licenses\" -prune -o \
            -type d -name \"__pycache__\" -prune -o \
            -type d -name \"node_modules\" -prune -o \
            -regex \".*[.]md\" \
            -exec \
              markdown-link-check \
                --quiet \
                --config \"./.markdown-link-check.json\" \
                \\{\\} \
                +
        "
    deps:
      - task: docs:generate
      - task: npm:install-deps
        vars:
          PROJECT_PATH: .
    cmds:
      - |
        npx \
          --package=markdown-link-check \
          --call='{{.CHECK_LINKS_COMMAND}}'

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:fix:
    desc: Automatically correct linting violations in Markdown files where possible
    deps:
      - task: npm:install-deps
        vars:
          PROJECT_PATH: .
    cmds:
      - |
        npx \
          markdownlint-cli \
            --fix \
            "**/*.md"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:lint:
    desc: Check for problems in Markdown files
    deps:
      - task: npm:install-deps
        vars:
          PROJECT_PATH: .
    cmds:
      - |
        npx \
          markdownlint-cli \
            "**/*.md"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-toc-task/Taskfile.yml
  markdown:toc:
    desc: |
      Update the table of contents.
      Environment variable parameters:
      - MAX_DEPTH: maximum heading depth for inclusion in ToC.
      - FILE_PATH: path to the file that contains the ToC.
    deps:
      - task: npm:install-deps
        vars:
          PROJECT_PATH: .
    cmds:
      - |
        npx \
          markdown-toc \
            --bullets=- \
            --maxdepth={{.MAX_DEPTH}} \
            -i \
            "{{.FILE_PATH}}"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/npm-task/Taskfile.yml
  npm:install-deps:
    desc: |
      Install dependencies managed by npm.
      Environment variable parameters:
      - PROJECT_PATH: Path of the npm-managed project (default: {{.DEFAULT_NPM_PROJECT_PATH}}).
    run: when_changed
    dir: "{{default .DEFAULT_NPM_PROJECT_PATH .PROJECT_PATH}}"
    cmds:
      - npm install

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/poetry-task/Taskfile.yml
  poetry:install:
    desc: Install Poetry
    run: when_changed
    cmds:
      - |
        if
          ! which go \
          &>/dev/null
        then
          echo "Go not found or not in PATH."
          echo "Please install: https://go.dev/doc/install"
          exit 1
        fi
      - |
        if
          ! which python \
          &>/dev/null
        then
          python_constraint="$( \
            go tool \
              yq \
                --input-format toml \
                --output-format yaml \
                '.tool.poetry.dependencies.python' \
            <pyproject.toml
          )"

          echo "Python not found or not in PATH."
          echo "Please install a version of Python satisfying the constraint ${python_constraint}:"
          echo "https://wiki.python.org/moin/BeginnersGuide/Download"
          exit 1
        fi
      - |
        if
          ! which pipx \
          &>/dev/null
        then
          echo "pipx not found or not in PATH."
          echo "Please install: https://pipx.pypa.io/stable/installation/#installing-pipx"
          exit 1
        fi
      - |
        export PIPX_DEFAULT_PYTHON="$( \
          go tool \
            task utility:normalize-path \
              RAW_PATH="$(which python)" \
        )"

        poetry_constraint="$( \
          go tool \
            yq \
              --input-format toml \
              --output-format yaml \
              '.tool.poetry.group.pipx.dependencies.poetry' \
          <pyproject.toml
        )"

        pipx install \
          --force \
          "poetry==$poetry_constraint"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/poetry-task/Taskfile.yml
  poetry:install-deps:
    desc: |
      Install dependencies managed by Poetry.
      Environment variable parameters:
      - POETRY_GROUPS: Poetry dependency groups to install (default: install all dependencies).
    run: when_changed
    deps:
      - task: poetry:install
    cmds:
      - |
        poetry install \
          {{if .POETRY_GROUPS}} --only {{.POETRY_GROUPS}} {{end}}

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-poetry-task/Taskfile.yml
  poetry:sync:
    desc: Sync Poetry lockfile
    deps:
      - task: poetry:install
    cmds:
      - |
        poetry lock \
          --no-cache

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-poetry-task/Taskfile.yml
  poetry:validate:
    desc: Validate Poetry configuration
    deps:
      - task: poetry:install
    cmds:
      - |
        poetry check \
          --lock \
          --strict

  # Print a normalized version of the path to stdout.
  # Environment variable parameters:
  # - RAW_PATH: the path to be normalized.
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/windows-task/Taskfile.yml
  utility:normalize-path:
    cmds:
      - |
        if
          [[ "{{.OS}}" == "Windows_NT" ]] \
          && \
          which cygpath \
          &>/dev/null
        then
          # Even though the shell handles POSIX format absolute paths as expected, external applications do not.
          # So paths passed to such applications must first be converted to Windows format.
          cygpath \
            -w \
            "{{.RAW_PATH}}"
        else
          echo "{{.RAW_PATH}}"
        fi
